const cards = [
    {
        title: 'Implement Authentication',
        description: 'Add Google OAuth using Passport.js.',
        list: 1,
        board: 1,
        labels: ['authentication', 'backend'],
        dueDate: '2024-07-25',
        order: 0,
        archived: false,
    },
    {
        title: 'Create Database Schema',
        description: 'Design and implement the SQLite database schema.',
        list: 1,
        board: 1,
        labels: ['database', 'backend'],
        dueDate: '2024-07-20',
        order: 1,
        archived: false,
    },
    {
        title: 'Setup Express Server',
        description: 'Initialize and configure the Express server.',
        list: 1,
        board: 2,
        labels: ['backend', 'server'],
        dueDate: '2024-07-18',
        order: 2,
        archived: false,
    },
    {
        title: 'Design Login Page',
        description:
            'Create a responsive login page using React and Tailwind CSS.',
        list: 2,
        board: 1,
        labels: ['frontend', 'design'],
        dueDate: '2024-07-19',
        order: 0,
        archived: false,
    },
    {
        title: 'Integrate Datadog',
        description: 'Add Datadog for monitoring and logging.',
        list: 2,
        board: 2,
        labels: ['monitoring', 'backend'],
        dueDate: '2024-07-21',
        order: 1,
        archived: false,
    },
    {
        title: 'Drag and Drop',
        description: 'Implement drag and drop functionality for cards.',
        list: 2,
        board: 3,
        labels: ['frontend', 'feature'],
        dueDate: '2024-07-22',
        order: 2,
        archived: false,
    },
    {
        title: 'Create Signup Page',
        description: 'Design and implement the signup page.',
        list: 3,
        board: 1,
        labels: ['frontend', 'design'],
        dueDate: '2024-07-23',
        order: 0,
        archived: false,
    },
    {
        title: 'Write Unit Tests',
        description: 'Write unit tests for the authentication module.',
        list: 3,
        board: 2,
        labels: ['testing', 'backend'],
        dueDate: '2024-07-24',
        order: 1,
        archived: false,
    },
    {
        title: 'Deploy to Production',
        description: 'Deploy the application to the production environment.',
        list: 3,
        board: 3,
        labels: ['deployment', 'backend'],
        dueDate: '2024-07-26',
        order: 2,
        archived: true,
    },
];

export default cards;
